# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    enable_automatic_code_signing
    match(type: 'appstore', readonly: true) # alias for sync_code_signing
    # sync_code_signing(type: 'appstore')
    increment_build_number(xcodeproj: "PushReact.xcodeproj")
    build_app(
                workspace: "PushReact.xcworkspace",
                scheme: "PushReact",
                export_method: "app-store"
              )
    upload_to_testflight
  end
end
